Add leveling function
kelyAna/moveit-nlw4 pull request #13
Opened 2021-02-25 13:42 UTC by kelyAna

2021-02-25 14:09 UTC, leandrakelly approved these changes

2021-02-25 17:46 UTC, leandrakelly approved these changes

2021-02-25 17:57 UTC, leandrakelly approved these changes

2021-02-25 18:08 UTC, AlysonBasilio commented on moveit-next/src/components/ChallengeBox.tsx
> +import { CountDownContext } from '../contexts/CountDownContex';
😅 
```suggestion
import { CountDownContext } from '../contexts/CountDownContext';
```

2021-02-25 18:10 UTC, AlysonBasilio commented on moveit-next/src/components/CountDown.tsx
> +                )}
O que houve aqui?

2021-02-25 18:19 UTC, AlysonBasilio requested changes
Dá uma olhadinha nos comentários que fiz

2021-02-26 16:23 UTC, GuilhermRodrigues approved these changes

2021-02-26 17:17 UTC, samueljrz approved these changes

2021-02-26 18:09 UTC, merged